---
postgres_users:
  - name: flask
    password: redhat
    database: flask_db
    state: present
    priv: ALL

postgres_databases:
  - name: flask_db
    owner: flask
  - name: books_store
    owner: flask
#postgres_rhel7_repo: "https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
#postgres_library: python-psycopg2
postgres_packages:
  - postgresql
  - postgresql-server
  - postgresql-contrib
  - postgresql-libs
#postgres_library: python-psycopg2
postgres_9_data_dir: /var/lib/pgsql/data
postgres_9_bin_path: /usr/pgsql/bin
postgres_service: postgresql.service
postgres_port: 5432
postgres_user: postgres

