---
# tasks file for roles/osp-instance-delete
- name: Delete instances
  os_server:
    cloud: openstack
    name: "{{ item.name }}"
    state: absent
  with_items: "{{result.openstack_servers}}"
#  loop: "{{ osp_servers }}"
