- name: Configuration of Public and Private Networks
  os_network:
    cloud: "{{ item.value.cloud_name }}"
    state: "{{ item.value.state }}"
    name: "{{ item.value.network_name }}"
    external: "{{ item.value.external }}"
    admin_state_up: "{{ item.value.admin_state }}"
    provider_network_type: "{{ item.value.provider_network_type | default(omit) }}"
    provider_physical_network: "{{ item.value.provider_physical_network | default(omit) }}"
  with_dict: "{{ osp_networks }}"

- name: Configuration of Subnets for Public and Private SubNets
  os_subnet:
    cloud: "{{ item.value.cloud_name }}"
    state: "{{ item.value.state }}"
    network_name: "{{ item.value.network_name  }}"
    name: "{{ item.value.subnet_name  }}"
    cidr: "{{ item.value.cidr_network }}"
    dns_nameservers:
      - 8.8.8.7
      - 8.8.8.8
    host_routes:
      - destination: 192.168.0.0/24
        nexthop: 192.168.0.1
      - destination: 0.0.0.0/0
        nexthop: 192.168.0.254
  with_dict: "{{ osp_networks }}"

- name: Create Router
  os_router:
    cloud: "{{ item.value.cloud_name }}"
    state: "{{ item.value.state }}"
    name: "{{ item.value.name }}"
    network: "{{ item.value.network }}"
    external_fixed_ips:
      - { subnet: ext_subnet }
    interfaces:
      - int_subnet
  with_dict: "{{ osp_router }}"